### Get All posts
GET http://localhost:3001/api/post/allpost
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBkYWJiZDljYmE3MDAzMjk1NDJhMjMiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcxMjE3MTk2NSwiZXhwIjoxNzE0NzYzOTY1fQ._by1Zj-xIdomc6grXkOvzGCwClf6kwoBoIZMhK4shLU

### Get A post
GET http://localhost:3001/api/post/6615f0ea87aa6360551f89d1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjE1ZmI2OTU5Y2Q4ZDJlNzk5Yjc4ZTAiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtMjAwMCIsImlhdCI6MTcxMjcxNjY0OSwiZXhwIjoxNzE1MzA4NjQ5fQ.3IFt49Iv93TpFqh-e_V-SON_QBrqS_F1YbvKt9p0AeQ